# Generated by Django 2.2.7 on 2020-10-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='top10cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Species', models.CharField(blank=True, max_length=100)),
                ('CS_information', models.CharField(blank=True, max_length=1000)),
                ('General_appearance_and_behavior', models.CharField(blank=True, max_length=100)),
                ('Gaab_information', models.CharField(max_length=1000)),
                ('husbandry', models.CharField(blank=True, max_length=100)),
                ('h_information', models.CharField(blank=True, max_length=1000)),
                ('imglink', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Question')),
            ],
        ),
    ]
