# Generated by Django 2.2.7 on 2020-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecat', models.CharField(blank=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('imglink', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
