# Generated by Django 3.1.2 on 2020-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='topcats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Species', models.CharField(max_length=200)),
                ('General_appearance_and_behavior', models.CharField(max_length=200)),
                ('husbandry', models.CharField(max_length=200)),
            ],
        ),
    ]
