# Generated by Django 3.1.2 on 2020-10-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_topcats'),
    ]

    operations = [
        migrations.CreateModel(
            name='top10cats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Species', models.CharField(max_length=200)),
                ('CS_information', models.CharField(max_length=200)),
                ('General_appearance_and_behavior', models.CharField(max_length=200)),
                ('Gaab_information', models.CharField(max_length=200)),
                ('husbandry', models.CharField(max_length=200)),
                ('h_information', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='topcats',
        ),
    ]
