# Generated by Django 3.1.2 on 2020-10-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20201003_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='top10cats',
            new_name='top10cat',
        ),
    ]
