# Generated by Django 3.1.2 on 2020-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20201004_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top10cat',
            name='CS_information',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='top10cat',
            name='Cat_Species',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='top10cat',
            name='Gaab_information',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='top10cat',
            name='General_appearance_and_behavior',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='top10cat',
            name='h_information',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='top10cat',
            name='husbandry',
            field=models.CharField(max_length=100),
        ),
    ]
